### PR TITLE
No key

### PR DESCRIPTION
**Pull request by gitmach**
removed unused ssh config
changed to http download

### CODE REVIEW

**Review by cpjagan — APPROVED** [review]
Changes look good.

**Comment by cpjagan** [comment]
@gitmach We will not need the ssh proxy config as well since we are using https and not git+ssh. I recommend that we remove that as well.

**Comment by jacmarjorie** [comment]
+1

**Review by jacmarjorie — APPROVED** [review]
Looks good.

**Review by cpjagan — APPROVED** [review]
updated changes are good.

**Pull request merged**
